# See GitHub's docs for more information on this file:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
# registries:
#   dockerhub: # Define access for a private registry
#     type: docker-registry
#     url: registry.hub.docker.com
#     # 
#     #username: 
#     #password: 
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    # registries:
    #   - dockerhub
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every weekday
      interval: "daily"
