# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Build (& Test)
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will 
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.
  # schedule:
  #   - cron: '0 13 * * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get Tools
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: toolInstall
    - name: Build
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: build
    - name: Lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
    - name: VulnCheck
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: vuln
    
  # test:
  #   name: Test
  #   needs: build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   strategy:
  #     fail-fast: false
  #   steps:
  #   - name: Set up Go
  #     uses: actions/setup-go@v2.1.3
  #     with:
  #       go-version: '1.16'
  #     id: go

  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2.3.3

  #   - name: Get Tools
  #     uses: magefile/mage-action@v2
  #     with:
  #       version: latest
  #       args: toolInstall
  #   - name: Test
  #     timeout-minutes: 10
  #     uses: magefile/mage-action@v2
  #     with:
  #       version: latest
  #       args: test
       